# Generated by Django 2.2.9 on 2020-12-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UserToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.UserSize')),
                ('user_toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.UserToppings')),
            ],
        ),
    ]
